begin;
insert into auth.users(id,email,aud,role,email_confirmed_at,created_at,updated_at)
values('11111111-1010-4010-8010-111111111111','credits-test@example.invalid','authenticated','authenticated',now(),now(),now());
insert into public.account_profiles(user_id,full_name) values('11111111-1010-4010-8010-111111111111','Credits test') on conflict do nothing;
update public.community_members set club_access_status='active',club_pro_status='active' where user_id='11111111-1010-4010-8010-111111111111';
set local role service_role;
do $$ declare member uuid:='11111111-1010-4010-8010-111111111111'; r jsonb; blocked boolean; purchase uuid; before_balance integer; begin
  update public.club_credit_settings set allowance=30,period='day',sales_active=false where id;
  update public.club_credit_costs set credits=1;
  insert into public.club_credit_periods(user_id,period,starts_on,used) values(member,'day',(now() at time zone 'UTC')::date,29);
  r:=public.reserve_club_credit_agent_turn(member,'Last included question');
  assert r->>'funding'='club','Included allowance first';
  blocked:=false;
  begin perform public.reserve_club_credits(member,'personalized_cv'); exception when others then blocked:=sqlerrm like '%QUESTION_IN_PROGRESS%'; end;
  assert blocked,'Concurrent generations cannot race across features';
  perform public.finish_club_agent_turn((r->>'turn_id')::uuid,'Answer','[]',false);
  blocked:=false;
  begin perform public.reserve_club_credits(member,'agent_question'); exception when others then blocked:=sqlerrm like '%INSUFFICIENT_CREDITS%'; end;
  assert blocked,'Insufficient balance blocks before generation';
  insert into public.club_member_api_keys values(member,'v1.'||repeat('x',60),'1234',now());
  r:=public.reserve_club_credits(member,'agent_question');assert r->>'funding'='api','Overflow uses own API';
  perform public.finish_club_credits((r->>'id')::uuid,true);
  perform public.finish_club_credits((r->>'id')::uuid,true);
  assert (select used=30 from public.club_credit_periods where user_id=member),'API failure does not refund unrelated Club credits';
  blocked:=false;
  begin perform public.create_club_credit_order(member); exception when others then blocked:=sqlerrm like '%SALES_CLOSED%'; end;
  assert blocked,'Unpriced sales remain closed';
  update public.club_credit_settings set pack_credits=10,pack_price_cents=1000,sales_active=true where id;
  purchase:=public.create_club_credit_order(member);
  assert public.create_club_credit_order(member)=purchase,'One pending order per member';
  update public.club_credit_settings set pack_credits=100,pack_price_cents=2000 where id;
  assert (select credits=10 and price_cents=1000 from public.club_credit_orders where id=purchase),'Order fixes original price and amount';
  blocked:=false;
  begin perform public.approve_club_credit_order(purchase,member); exception when others then blocked:=sqlerrm like '%ORDER_NOT_SUBMITTED%'; end;
  assert blocked,'Unsubmitted payment cannot credit wallet';
  update public.club_credit_orders set status='submitted',receipt_path='test/receipt' where id=purchase;
  perform public.approve_club_credit_order(purchase,member);
  perform public.approve_club_credit_order(purchase,member);
  assert (select purchased=10 from public.club_credit_wallets where user_id=member),'Duplicate approval credits once';
  update public.club_credit_costs set credits=3 where action='personalized_cv';
  r:=public.reserve_club_credits(member,'personalized_cv');assert r->>'funding'='club','Purchased credits before API';
  assert (select purchased=7 from public.club_credit_wallets where user_id=member),'Action-specific cost';
  perform public.finish_club_credits((r->>'id')::uuid,true);perform public.finish_club_credits((r->>'id')::uuid,true);
  assert (select purchased=10 from public.club_credit_wallets where user_id=member),'Refund once';
  update public.club_credit_periods set used=28 where user_id=member;
  r:=public.reserve_club_credits(member,'personalized_cv');
  assert (select included=2 and purchased=1 from public.club_credit_transactions where id=(r->>'id')::uuid),'Combine allowance and purchased balance';
  perform public.finish_club_credits((r->>'id')::uuid,false);
  perform public.finish_club_credits((r->>'id')::uuid,true);
  assert (select purchased=9 from public.club_credit_wallets where user_id=member),'Completed generation cannot be refunded by duplicate settlement';
  delete from public.club_agent_conversations where user_id=member;
  assert (select used=30 from public.club_credit_periods where user_id=member),'Deleting conversation preserves consumption';
  update public.club_credit_settings set period='month' where id;
  r:=public.reserve_club_credits(member,'agent_summary');assert r->>'funding'='club','New period has own allowance';
  perform public.finish_club_credits((r->>'id')::uuid,true);
  r:=public.reserve_club_credit_agent_turn(member,'Abandoned generation');
  update public.club_credit_transactions set created_at=now()-interval '6 minutes' where id=(r->>'id')::uuid;
  perform public.recover_club_credits(member);perform public.recover_club_credits(member);
  assert (select used=0 from public.club_credit_periods where user_id=member and period='month'),'Abandoned request refunds once';
  assert (select status='failed' from public.club_agent_turns where id=(r->>'turn_id')::uuid),'Abandoned agent turn is closed';
  update public.community_members set club_pro_status='inactive' where user_id=member;
  blocked:=false;begin perform public.reserve_club_credits(member,'personalized_cv');exception when others then blocked:=sqlerrm like '%PRO_REQUIRED%';end;
  assert blocked,'API key and purchased balance do not bypass Pro';
end $$;
reset role;
select set_config('request.jwt.claim.sub','22222222-1010-4010-8010-222222222222',true);
set local role authenticated;
do $$ begin
  assert not exists(select 1 from public.club_credit_wallets),'Foreign wallet hidden';
  assert not exists(select 1 from public.club_credit_transactions),'Foreign ledger hidden';
  assert not exists(select 1 from public.club_credit_orders),'Foreign orders hidden';
  assert not has_table_privilege('authenticated','public.club_credit_wallets','update'),'Cannot forge balances';
  assert not has_function_privilege('authenticated','public.reserve_club_credits(uuid,text)','execute'),'Cannot forge billing owner';
  assert not has_function_privilege('authenticated','public.approve_club_credit_order(uuid,uuid)','execute'),'Cannot approve own purchase';
  assert not has_function_privilege('anon','public.configure_club_credits(integer,text,integer,integer,boolean,jsonb)','execute'),'Cannot change prices';
end $$;
reset role;
select 'Credit wallet: funding, concurrency, refunds, purchases, ownership and entitlement assertions passed' as result;
rollback;
