'use client'
import { useClubLanguage } from '@/components/community/ClubLanguage'

import Link from 'next/link'
import {usePathname} from 'next/navigation'
import {CalendarDays, MessageCircle, Users, FileText, MessageSquareText, Wrench} from 'lucide-react'
import { COMMUNITY_CATEGORIES } from '@/lib/community'
const items=[{href:'/community',label:'Comunidade',icon:MessageCircle},{href:'/community/calendar',label:'Eventos',icon:CalendarDays},{href:'/community/tools',label:'Ferramentas',icon:Wrench}]
const forumKeys=['discussao','cases','ia-automacao','dados-metricas','contratos-clm','processos-projetos','ferramentas','financeiro-fornecedores','governanca-conhecimento','estrategia-maturidade','modelos-entrega','carreira']
export function CommunityTabs(){
 const { t } = useClubLanguage()
const path=usePathname();return <><aside className="hidden lg:block lg:w-64 lg:shrink-0 lg:border-r lg:border-[#CEC8BD] lg:bg-[#F5F1E8] lg:px-4 lg:py-6"><Link href="/community" className="flex items-center gap-2 px-3 text-sm font-extrabold">LegalOps Club</Link><p className="mt-7 px-3 text-[9px] font-black uppercase tracking-[0.14em] text-[#999690]">{t("Navegação")}</p><div className="mt-2 space-y-1">{[["/community",t("Comunidade"),MessageCircle],["/community/calendar",t("Eventos"),CalendarDays],["/community/tools",t("Ferramentas"),Wrench],["/community/members",t("Membros"),Users],["/community/summaries",t("Resumos do WhatsApp"),FileText]].map(([href,label,Icon])=><Link key={href as string} href={href as string} className={`flex min-h-11 items-center gap-2 rounded-lg px-3 text-xs font-semibold ${(href==='/community'?path==='/community':path.startsWith(href as string))?'bg-[#E9E4D9] text-[#A94E38]':'text-[#625E59]'}`}><Icon className="h-4 w-4"/>{t(label as string)}</Link>)}</div><p className="mt-7 px-3 text-[9px] font-black uppercase tracking-[0.14em] text-[#999690]">{t("Fóruns por assunto")}</p><div className="mt-2 max-h-[42dvh] space-y-1 overflow-y-auto">{forumKeys.map(key=><Link key={key} href={`/community?space=${key}`} className={`flex min-h-10 items-center gap-2 rounded-lg px-3 text-[11px] font-semibold ${path==='/community'?'text-[#625E59]':'text-[#625E59]'}`}><MessageSquareText className="h-3.5 w-3.5 text-[#C9684F]"/>{t(COMMUNITY_CATEGORIES[key].label)}</Link>)}</div><p className="mt-6 rounded-lg bg-white/60 px-3 py-3 text-[10px] leading-4 text-[#716B65]">{t("No app, organizamos por assunto. No WhatsApp, a conversa é geral para não fechar a comunidade em um único tema.")}</p></aside><nav aria-label={t("Áreas do Club")} className="club-bottom-nav fixed inset-x-0 bottom-0 z-40 grid grid-cols-3 border-t border-[#CEC8BD] bg-[#F5F1E8] px-2 pt-1 lg:hidden">{items.map(item=>{const active=item.href==='/community'?path===item.href:path.startsWith(item.href)||(item.href==='/community/calendar'&&path.startsWith('/community/events/'));return <Link key={item.href} href={item.href} aria-current={active?'page':undefined} className={`flex min-h-14 items-center justify-center gap-2 rounded-xl text-xs font-semibold sm:text-sm ${active?'bg-[#E9E4D9] text-[#A94E38]':'text-[#625E59]'}`}><item.icon className="h-4 w-4 shrink-0"/>{t(item.label)}</Link>})}</nav></>}
