import {normalize,validate,markdown,proposalUrl} from './model.mjs';
const form=document.getElementById('draft'),key='legalops-open-playbook-v1',status=document.getElementById('save-status');
try{const saved=normalize(JSON.parse(localStorage.getItem(key)));for(const [name,value]of Object.entries(saved))form.elements[name].value=value}catch{}
const read=()=>normalize(Object.fromEntries(new FormData(form)));
function invalidate(){document.getElementById('proposal').hidden=true;document.getElementById('consent').checked=false;document.getElementById('contribute').hidden=true;document.getElementById('contribute').removeAttribute('href')}
form.addEventListener('input',()=>{invalidate();try{localStorage.setItem(key,JSON.stringify(read()));status.textContent='Rascunho salvo neste navegador.'}catch{status.textContent='Não foi possível salvar no navegador. Baixe o texto para guardar.'}});
form.addEventListener('submit',event=>{event.preventDefault();if(!validate(read()))return;document.getElementById('preview').textContent=markdown(read());document.getElementById('proposal').hidden=false;document.getElementById('proposal').scrollIntoView({block:'start'})});
function download(json=false){const v=read();const url=URL.createObjectURL(new Blob([json?JSON.stringify({version:'0.1.0',status:'proposal',...v},null,2):markdown(v)],{type:json?'application/json':'text/markdown;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=json?'playbook-proposta.json':'playbook-proposta.md';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
document.getElementById('download').addEventListener('click',()=>download());document.getElementById('json').addEventListener('click',()=>download(true));
document.getElementById('consent').addEventListener('change',event=>{const link=document.getElementById('contribute');link.hidden=!event.target.checked;if(event.target.checked)link.href=proposalUrl(read());else link.removeAttribute('href')});
fetch('/playbook/library.json').then(r=>{if(!r.ok)throw Error();return r.json()}).then(({entries})=>{document.getElementById('library-status').textContent=entries.length?`${entries.length} posições revisadas. Valide a adequação ao seu contexto.`:'Ainda não há posições aprovadas. As primeiras contribuições serão revisadas antes de aparecer aqui.';for(const entry of entries){const article=document.createElement('article'),title=document.createElement('h3'),text=document.createElement('p');title.textContent=entry.topic;text.textContent=entry.position;article.append(title,text);document.getElementById('library').append(article)}}).catch(()=>{document.getElementById('library-status').textContent='Não foi possível carregar a biblioteca. Tente novamente.'});
