'use client'
import { useMemo } from 'react'
import { mapChanges } from '@/lib/map-diff'
import type { MapNode } from '@/lib/contract-map'
import { MapContent } from './MapContent'
export function ChangeReview({before,after,decisions,onChange}: {before:MapNode;after:MapNode;decisions:(boolean|null)[];onChange:(value:(boolean|null)[])=>void}){
 const changes=useMemo(()=>mapChanges(before,after).filter(change=>change.changed),[before,after])
 function decide(index:number,value:boolean){const next=changes.map((_,i)=>decisions[i]??null);next[index]=value;onChange(next)}
 return <section aria-label="Revisão das alterações" className="mt-4 space-y-4"><div className="flex flex-wrap items-center justify-between gap-2"><p className="text-sm font-semibold">{changes.length} alterações por bloco</p><button type="button" onClick={()=>onChange(changes.map(()=>true))} className="min-h-11 text-sm underline">Aceitar todas</button></div>{changes.length===0&&<p className="text-sm">A proposta é igual ao texto atual.</p>}{changes.map((change,index)=><article key={index} className="overflow-hidden rounded-xl border border-[#CEC8BD]"><div className="grid gap-1 md:grid-cols-2"><div className="min-w-0 bg-red-50 p-3"><p className="mb-2 text-xs font-semibold text-red-800">− Texto atual</p>{change.before.length?<MapContent content={{type:'doc',content:change.before}}/>:<p className="text-xs">Bloco novo</p>}</div><div className="min-w-0 bg-green-50 p-3"><p className="mb-2 text-xs font-semibold text-green-800">+ Texto proposto</p>{change.after.length?<MapContent content={{type:'doc',content:change.after}}/>:<p className="text-xs">Remoção do bloco</p>}</div></div><div className="flex flex-wrap gap-3 bg-white p-3 text-sm"><button type="button" aria-pressed={decisions[index]===true} onClick={()=>decide(index,true)} className={`min-h-11 rounded-lg border px-3 ${decisions[index]===true?'border-green-700 bg-green-50':'border-[#CEC8BD]'}`}>Aceitar alteração {index+1}</button><button type="button" aria-pressed={decisions[index]===false} onClick={()=>decide(index,false)} className={`min-h-11 rounded-lg border px-3 ${decisions[index]===false?'border-red-700 bg-red-50':'border-[#CEC8BD]'}`}>Manter texto atual</button></div></article>)}<p className="text-xs text-[#625E59]">Cada decisão preserva a formatação do bloco escolhido. A publicação reúne apenas as mudanças aceitas e registra a versão resultante.</p></section>
}
