'use client'
import { useEffect, useRef, useState } from 'react'
import { MentionField } from './MentionField'
import type { CommentAnchor } from '@/lib/map-comments'
export function CommentComposer({section,version,quote,anchor,parent,onSent,onClose,modal=false}: {section:string;version:number;quote?:string;anchor?:CommentAnchor;parent?:string;onSent:(id?:string)=>void;onClose?:()=>void;modal?:boolean}) {
 const [note,setNote]=useState('');const [mentions,setMentions]=useState<string[]>([]);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const dialog=useRef<HTMLDialogElement>(null)
 useEffect(()=>{if(modal)dialog.current?.showModal();return()=>dialog.current?.close()},[modal])
 async function submit(event:React.FormEvent){event.preventDefault();event.stopPropagation();setBusy(true);setError('');try{const result=await fetch('/api/community/contract-map',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'comment',section,version,note,mentions,...(quote?{quote}:{}),...(anchor?{anchor}:{}),...(parent?{parent}:{})})});const data=await result.json();if(!result.ok)throw new Error(data.error);setNote('');setMentions([]);onSent(data.id);onClose?.()}catch(error){setError(error instanceof Error?error.message:'Não foi possível comentar.')}finally{setBusy(false)}}
 const form=<form onSubmit={submit} className="space-y-3"><h3 className="font-semibold">{parent?'Responder à conversa':quote?'Comentar este trecho':'Pergunta ou comentário'}</h3>{quote&&<blockquote className="max-h-32 overflow-y-auto border-l-2 border-[#A94E38] pl-3 text-sm text-[#625E59]">“{quote}”<span className="mt-1 block text-xs">Trecho indicado na construção da versão {version}</span></blockquote>}<MentionField value={note} onChange={setNote} onMentions={setMentions} label="Sua contribuição"/>{error&&<p role="alert" className="text-sm text-red-700">{error}</p>}<div className="flex gap-2"><button disabled={busy} className="min-h-11 rounded-xl bg-[#24231F] px-4 py-2 text-sm font-semibold text-white disabled:opacity-50">{busy?'Enviando…':'Publicar comentário'}</button>{onClose&&<button type="button" disabled={busy} onClick={onClose} className="min-h-11 rounded-xl border px-4 text-sm">Cancelar</button>}</div></form>
 return modal?<dialog ref={dialog} onCancel={onClose} aria-label="Comentário no documento" className="w-[calc(100vw_-_2rem)] max-h-[calc(100dvh_-_2rem)] overflow-y-auto max-w-lg rounded-2xl border border-[#CEC8BD] p-5 backdrop:bg-black/40">{form}</dialog>:<div className="rounded-2xl border border-[#CEC8BD] bg-white p-4">{form}</div>
}
