import type { ClubLocale } from './club-locale'
const pt = {
  title:'Créditos do Pro', included:'Incluídos disponíveis', purchased:'Créditos comprados', daily:'por dia', monthly:'por mês',
  rules:'Primeiro usamos a franquia do Pro, depois os créditos comprados. Se o saldo não cobrir a ação, usamos sua API conectada, sem descontar créditos do Club. A OpenAI cobra esse consumo diretamente na sua conta.',
  reset:'A franquia renova às 00h UTC (21h de Brasília); créditos incluídos não acumulam. Créditos comprados não expiram e exigem Pro ativo para uso.',
  costs:'Custo por geração concluída', history:'Extrato recente', buy:'Comprar créditos por PIX', closed:'Pacotes de créditos em preparação.',
  question:'Pergunta ao agente', summary:'Resumo do agente', cv:'Currículo personalizado', letter:'Carta de apresentação', interview:'Preparação para entrevista', linkedin:'Análise de perfil', purchase:'Compra de créditos',
  apiFailed:'Falha na API · consulte o consumo na OpenAI', pending:'Em processamento', completed:'Concluído', failed:'Falhou · créditos devolvidos', api:'Uso da API pessoal', club:'Créditos do Club',
  manage:'Saldo e créditos', loading:'Carregando créditos…', unavailable:'Não conseguimos carregar os créditos.',
  insufficient:'Créditos insuficientes. Compre créditos extras ou conecte sua chave de API no perfil.',
  required:'Este recurso exige Pro ativo.', busy:'Aguarde a geração anterior terminar.',
  nextApi:'A próxima geração usará sua API OpenAI, com cobrança na sua conta.',
  cost:'crédito(s) por geração', choose:'Ação do agente',
}
const en:typeof pt={title:'Pro credits',included:'Included credits available',purchased:'Purchased credits',daily:'per day',monthly:'per month',rules:'We use your Pro allowance first, then purchased credits. If the balance cannot cover the action, we use your connected API without spending Club credits. OpenAI bills that usage directly to your account.',reset:'The allowance renews at 00:00 UTC; included credits do not roll over. Purchased credits do not expire and require active Pro access.',costs:'Cost per completed generation',history:'Recent activity',buy:'Buy credits via PIX',closed:'Credit packs are being prepared.',question:'Agent question',summary:'Agent summary',cv:'Personalized résumé',letter:'Cover letter',interview:'Interview preparation',linkedin:'Profile analysis',purchase:'Credit purchase',apiFailed:'API failed · check OpenAI usage',pending:'Processing',completed:'Completed',failed:'Failed · credits refunded',api:'Personal API usage',club:'Club credits',manage:'Balance and credits',loading:'Loading credits…',unavailable:'We could not load your credits.',insufficient:'Insufficient credits. Buy extra credits or connect your API key in your profile.',required:'This feature requires active Pro access.',busy:'Wait for the previous generation to finish.',nextApi:'The next generation will use your OpenAI API and be billed to your account.',cost:'credit(s) per generation',choose:'Agent action'}
const es:typeof pt={title:'Créditos Pro',included:'Créditos incluidos disponibles',purchased:'Créditos comprados',daily:'por día',monthly:'por mes',rules:'Primero usamos la franquicia Pro y después los créditos comprados. Si el saldo no cubre la acción, usamos tu API conectada sin descontar créditos del Club. OpenAI cobra ese consumo directamente en tu cuenta.',reset:'La franquicia se renueva a las 00:00 UTC; los créditos incluidos no se acumulan. Los comprados no caducan y requieren Pro activo.',costs:'Coste por generación completada',history:'Actividad reciente',buy:'Comprar créditos por PIX',closed:'Paquetes de créditos en preparación.',question:'Pregunta al agente',summary:'Resumen del agente',cv:'Currículum personalizado',letter:'Carta de presentación',interview:'Preparación de entrevista',linkedin:'Análisis de perfil',purchase:'Compra de créditos',apiFailed:'Falló la API · revisa el consumo en OpenAI',pending:'Procesando',completed:'Completado',failed:'Falló · créditos devueltos',api:'Uso de tu API personal',club:'Créditos del Club',manage:'Saldo y créditos',loading:'Cargando créditos…',unavailable:'No pudimos cargar los créditos.',insufficient:'Créditos insuficientes. Compra créditos adicionales o conecta tu clave de API en el perfil.',required:'Este recurso requiere Pro activo.',busy:'Espera a que termine la generación anterior.',nextApi:'La próxima generación usará tu API de OpenAI y se cobrará en tu cuenta.',cost:'crédito(s) por generación',choose:'Acción del agente'}
export const creditCopy=(locale:ClubLocale)=>locale==='en'?en:locale==='es'?es:pt
export function creditActionLabel(action:string,locale:ClubLocale){const c=creditCopy(locale);return ({agent_question:c.question,agent_summary:c.summary,personalized_cv:c.cv,cover_letter:c.letter,interview_prep:c.interview,linkedin_insights:c.linkedin,purchase:c.purchase} as Record<string,string>)[action]??action}
export function creditErrorMessage(code:string,locale:ClubLocale){const c=creditCopy(locale);return code==='INSUFFICIENT_CREDITS'?c.insufficient:code==='PRO_REQUIRED'?c.required:code==='QUESTION_IN_PROGRESS'?c.busy:c.unavailable}
