// Static interface translations; no model call is needed for directory controls.
const labels: Array<[string,string,string]> = [
 ['Encontre pessoas por experiência, função, qualificação ou região.','Find people by experience, role, qualifications or region.','Encuentra personas por experiencia, función, cualificación o región.'],
 ['Meu perfil e validação','My profile and verification','Mi perfil y verificación'],
 ['Cadastro','Profile status','Estado del perfil'],
 ['Cadastro completo','Complete profile','Perfil completo'],
 ['Cadastro incompleto','Incomplete profile','Perfil incompleto'],
 ['Perfil completo','Complete profile','Perfil completo'],
 ['Perfil incompleto','Incomplete profile','Perfil incompleto'],
 ['Fila de validação','Verification queue','Cola de verificación'],
 ['Pesquisar no diretório','Search the directory','Buscar en el directorio'],
 ['Nome, cargo, empresa, experiência, cidade…','Name, role, company, experience, city…','Nombre, cargo, empresa, experiencia, ciudad…'],
 ['Filtros avançados','Advanced filters','Filtros avanzados'],
 ['Estado / região','State / region','Estado / región'],
 ['Cidade','City','Ciudad'],
 ['Todos','All','Todos'],
 ['Especialidade','Specialty','Especialidad'],
 ['Qualificação','Qualification','Cualificación'],
 ['Validação','Verification','Verificación'],
 ['Em análise','Under review','En revisión'],
 ['Não validado','Not verified','Sin verificar'],
 ['Ordenar por','Sort by','Ordenar por'],
 ['Nome (A–Z)','Name (A–Z)','Nombre (A–Z)'],
 ['Mais recentes','Newest','Más recientes'],
 ['Limpar filtros','Clear filters','Quitar filtros'],
 ['O que significa a validação?','What does verification mean?','¿Qué significa la verificación?'],
 ['O que significa o selo?','What does the badge mean?','¿Qué significa el distintivo?'],
 ['O selo de perfil completo aparece automaticamente quando a foto e os campos profissionais obrigatórios estão preenchidos. As informações são declaradas pelo membro; o Club não certifica identidade, diplomas ou competências.','The complete-profile badge appears automatically when the photo and required professional fields are filled in. Information is self-reported; the Club does not certify identity, degrees or skills.','El distintivo de perfil completo aparece automáticamente cuando se completan la foto y los campos profesionales obligatorios. La información es declarada por cada miembro; el Club no certifica identidad, títulos ni competencias.'],
 ['Validado: a administração conferiu a identidade e o contexto profissional. Em análise: há uma solicitação na fila. Não validado: ainda não houve aprovação. O selo não certifica diplomas ou competências e não é requisito para participar da comunidade.','Verified: administrators checked the identity and professional context. Under review: a request is in the queue. Not verified: approval has not been granted. The badge does not certify degrees or skills and is not required to participate in the community.','Verificado: la administración comprobó la identidad y el contexto profesional. En revisión: hay una solicitud en la cola. Sin verificar: todavía no hay aprobación. El distintivo no certifica títulos ni competencias y no es un requisito para participar en la comunidad.'],
 ['Localização e qualificações são opcionais e declaradas pelos membros. Perfis sem esses dados não aparecem nos filtros correspondentes.','Location and qualifications are optional and self-reported. Profiles without these details do not appear in the corresponding filters.','La ubicación y las cualificaciones son opcionales y declaradas por cada miembro. Los perfiles sin estos datos no aparecen en los filtros correspondientes.'],
 ['Não foi possível carregar os membros. Seus filtros foram preservados.','Could not load members. Your filters have been preserved.','No se pudieron cargar los miembros. Se conservaron tus filtros.'],
 ['Nenhum perfil encontrado','No profiles found','No se encontraron perfiles'],
 ['Revise os termos ou remova filtros para ampliar a busca.','Check the terms or remove filters to broaden your search.','Revisa los términos o quita filtros para ampliar la búsqueda.'],
 ['Ver perfil completo','View full profile','Ver perfil completo'],
 ['Paginação','Pagination','Paginación'],
 ['Anterior','Previous','Anterior'],
 ['Próxima','Next','Siguiente'],
 ['Localização e qualificações no diretório','Directory location and qualifications','Ubicación y cualificaciones en el directorio'],
 ['Campos opcionais visíveis aos membros e usados nos filtros de busca. Informe apenas o que deseja compartilhar; preferências de vagas e currículo continuam separados.','Optional fields visible to members and used in search filters. Share only what you choose; job preferences and your résumé remain separate.','Campos opcionales visibles para los miembros y usados en los filtros. Comparte solo lo que desees; tus preferencias laborales y tu currículum siguen separados.'],
 ['Não informar','Do not share','No compartir'],
 ['Qualificações públicas','Public qualifications','Cualificaciones públicas'],
 ['Ex.: Direito, MBA, gestão de projetos, análise de dados','E.g. Law, MBA, project management, data analysis','Ej.: Derecho, MBA, gestión de proyectos, análisis de datos'],
 ['Separe por vírgulas. São informações declaradas por você, sem certificação pelo Club.','Separate with commas. These are self-reported details, not certified by the Club.','Separa con comas. Son datos declarados por ti, sin certificación del Club.'],
 ['Informações declaradas pelo membro, sem certificação pelo Club.','Self-reported details, not certified by the Club.','Datos declarados por el miembro, sin certificación del Club.'],
 ['A administração conferiu sua identidade e seu contexto profissional. O selo não certifica diplomas ou competências.','Administrators checked your identity and professional context. The badge does not certify degrees or skills.','La administración comprobó tu identidad y tu contexto profesional. El distintivo no certifica títulos ni competencias.'],
 ['Sua solicitação está na fila da administração. A decisão e eventuais pedidos de ajustes aparecerão aqui. Você pode continuar usando a comunidade.','Your request is in the administrator queue. The decision and any requested changes will appear here. You can continue using the community.','Tu solicitud está en la cola de administración. La decisión y los ajustes solicitados aparecerán aquí. Puedes seguir usando la comunidad.'],
 ['Ajustes solicitados','Changes requested','Ajustes solicitados'],
 ['Veja o motivo abaixo, atualize os dados necessários e solicite uma nova análise.','Read the reason below, update the required details and request another review.','Lee el motivo a continuación, actualiza los datos necesarios y solicita una nueva revisión.'],
 ['Validação não solicitada','Verification not requested','Verificación no solicitada'],
 ['Seu cadastro ainda não passou por conferência. Complete os campos indicados e solicite a análise da administração.','Your profile has not been checked yet. Complete the listed fields and request an administrator review.','Tu perfil todavía no se ha comprobado. Completa los campos indicados y solicita la revisión de la administración.'],
 ['A completude foi confirmada automaticamente. As informações são declaradas pelo membro e não representam certificação de identidade, diplomas ou competências.','Completeness was confirmed automatically. Information is self-reported and does not represent certification of identity, degrees or skills.','La completitud se confirmó automáticamente. La información es declarada por el miembro y no representa certificación de identidad, títulos ni competencias.'],
 ['Complete os campos obrigatórios para receber o selo automaticamente.','Complete the required fields to receive the badge automatically.','Completa los campos obligatorios para recibir el distintivo automáticamente.'],
 ['Falta completar','Still needed','Falta completar'],
 ['Foto','Photo','Foto'],
 ['O selo é atualizado automaticamente quando a foto e os campos profissionais obrigatórios estão completos.','The badge updates automatically when the photo and required professional fields are complete.','El distintivo se actualiza automáticamente cuando la foto y los campos profesionales obligatorios están completos.'],
 ['LinkedIn profissional','Professional LinkedIn','LinkedIn profesional'],
 ['Selo automático de cadastro completo','Automatic complete-profile badge','Distintivo automático de perfil completo'],
 ['Obrigatória','Required','Obligatoria'],
 ['A foto é obrigatória para concluir um novo cadastro. Membros que já participam podem completar o perfil depois. JPG, PNG ou WebP, até 10 MB.','A photo is required to complete a new registration. Existing members can complete their profile later. JPG, PNG or WebP, up to 10 MB.','La foto es obligatoria para completar un nuevo registro. Los miembros actuales pueden completar su perfil después. JPG, PNG o WebP, hasta 10 MB.'],
 ['Adicione sua foto para concluir o cadastro.','Add your photo to complete registration.','Añade tu foto para completar el registro.'],
 ['Adicione sua foto para liberar a entrada na comunidade.','Add your photo to enter the community.','Añade tu foto para entrar en la comunidad.'],
 ['Adicione uma foto para completar seu perfil.','Add a photo to complete your profile.','Añade una foto para completar tu perfil.'],
 ['Complete seu perfil','Complete your profile','Completa tu perfil'],
 ['Adicione uma foto e complete seus dados profissionais para receber o selo de perfil completo.','Add a photo and complete your professional details to receive the complete-profile badge.','Añade una foto y completa tus datos profesionales para recibir el distintivo de perfil completo.'],
 ['Completar agora','Complete now','Completar ahora'],
 ['Solicitação recebida. Acompanhe a decisão nesta área.','Request received. Follow the decision here.','Solicitud recibida. Consulta la decisión aquí.'],
 ['Não foi possível solicitar. Confira os campos indicados e tente novamente.','Could not submit the request. Check the listed fields and try again.','No se pudo enviar la solicitud. Comprueba los campos indicados e inténtalo de nuevo.'],
 ['Última solicitação','Latest request','Última solicitud'],
 ['Complete antes de solicitar','Complete before requesting','Completa antes de solicitar'],
 ['Solicitar validação','Request verification','Solicitar verificación'],
 ['Salve as alterações do perfil antes de solicitar.','Save profile changes before requesting verification.','Guarda los cambios del perfil antes de solicitar la verificación.'],
 ['A validação confere nome, cargo, organização e LinkedIn. Alterar esses dados exige nova análise. Não há prazo de conclusão definido.','Verification checks your name, role, organization and LinkedIn. Changing these details requires another review. No completion deadline is set.','La verificación comprueba nombre, cargo, organización y LinkedIn. Cambiar estos datos requiere otra revisión. No hay un plazo de resolución definido.'],
 ['No Playbook e em Migração de CLM, comente e proponha melhorias aqui no Club; membros-lead revisam antes da publicação.','Comment and suggest improvements to the Playbook and CLM Migration here in the Club; lead members review before publication.','Comenta y propón mejoras al Playbook y a la Migración de CLM aquí en el Club; los miembros líderes revisan antes de publicar.'],
]
export const directoryEnglish: Record<string,string> = Object.fromEntries(labels.map(([pt,en])=>[pt,en]))
export const directorySpanish: Record<string,string> = Object.fromEntries(labels.map(([pt,,es])=>[pt,es]))
