import Link from 'next/link'
import { createServerSupabaseClient } from '@/lib/supabase-server'
import { hasActiveClubAccess } from '@/lib/community'
import { registerPublicEvent, shareEventResource } from '../../actions'

export const dynamic = 'force-dynamic'

export default async function EventPage({ params, searchParams }: { params: { slug: string }, searchParams?: { registered?: string, shared?: string } }) {
  const supabase = await createServerSupabaseClient()
  const { data: { user } } = await supabase.auth.getUser()
  const { data: event } = await supabase.from('community_events').select('id,slug,title,description,host_name,starts_at,ends_at,location_label,location_url,event_type,is_published').eq('slug', params.slug).eq('is_published', true).maybeSingle()
  if (!event) return <div className="mx-auto max-w-2xl px-5 py-16"><h1 className="text-2xl font-bold">Evento não encontrado</h1><Link className="mt-4 inline-flex underline" href="/community/calendar">Voltar para eventos</Link></div>
  const { data: member } = await supabase.from('community_members').select('club_access_status,club_access_expires_at').eq('user_id', user?.id ?? '').maybeSingle()
  const isMember = hasActiveClubAccess(member)
  const { data: attendance } = user && isMember ? await supabase.from('community_event_rsvps').select('id,response').eq('event_id', event.id).eq('user_id', user.id).eq('response', 'confirmed').maybeSingle() : { data: null }
  const { data: eventAdmin } = user && isMember ? await supabase.from('community_event_admins').select('event_id').eq('event_id', event.id).eq('user_id', user.id).maybeSingle() : { data: null }
  const canContribute = Boolean(attendance || eventAdmin)
  const { data: resources } = canContribute ? await supabase.from('community_event_resources').select('id,title,description,kind,resource_url,storage_path,created_at').eq('event_id', event.id).order('created_at', { ascending: false }) : { data: [] }
  const { data: discussions } = isMember ? await supabase.from('community_posts').select('id,title,body,created_at').eq('event_id', event.id).order('created_at', { ascending: false }).limit(20) : { data: [] }
  const past = new Date(event.starts_at) < new Date()
  return <main className="mx-auto w-full max-w-3xl px-4 py-7 sm:px-6 lg:py-12">
    <Link href="/community/calendar" className="text-xs font-bold text-[#D9470F]">← Eventos</Link>
    <article className="mt-5 rounded-2xl border border-[#E1E1DD] bg-white p-5 sm:p-8">
      <p className="text-[9px] font-black uppercase tracking-[0.14em] text-[#D9470F]">{past ? 'Evento realizado' : 'Próximo evento'} · {event.event_type}</p>
      <h1 className="mt-3 text-2xl font-extrabold tracking-[-0.03em] text-[#24231F] sm:text-3xl">{event.title}</h1>
      <p className="mt-4 whitespace-pre-wrap text-sm leading-7 text-[#625E59]">{event.description}</p>
      <dl className="mt-6 grid gap-3 border-t border-[#ECECE8] pt-5 text-sm text-[#625E59] sm:grid-cols-2"><div><dt className="text-[9px] font-black uppercase tracking-wider text-[#999690]">Quando</dt><dd className="mt-1 font-semibold">{new Intl.DateTimeFormat('pt-BR',{dateStyle:'full',timeStyle:'short',timeZone:'America/Sao_Paulo'}).format(new Date(event.starts_at))}</dd></div><div><dt className="text-[9px] font-black uppercase tracking-wider text-[#999690]">Onde</dt><dd className="mt-1 font-semibold">{event.location_label}</dd></div><div><dt className="text-[9px] font-black uppercase tracking-wider text-[#999690]">Organização</dt><dd className="mt-1 font-semibold">{event.host_name}</dd></div></dl>
      {searchParams?.registered ? <p role="status" className="mt-6 rounded-lg bg-emerald-50 p-3 text-sm font-semibold text-emerald-800">Cadastro recebido. Para acessar materiais e discussões, entre na comunidade.</p> : null}
      {!isMember && !past ? <form action={registerPublicEvent} className="mt-7 rounded-xl bg-[#F5F1E8] p-4 sm:p-5"><input type="hidden" name="event_id" value={event.id} /><h2 className="font-bold">Reserve sua vaga</h2><p className="mt-1 text-xs leading-5 text-[#716B65]">O cadastro é público. Seu acesso aos materiais depois do encontro depende de uma conta da comunidade.</p><div className="mt-4 grid gap-3 sm:grid-cols-2"><input name="name" required minLength={2} placeholder="Nome" className="min-h-11 rounded-lg border bg-white px-3 text-sm" /><input name="email" required type="email" placeholder="E-mail" className="min-h-11 rounded-lg border bg-white px-3 text-sm" /><input name="role" required minLength={2} placeholder="Cargo" className="min-h-11 rounded-lg border bg-white px-3 text-sm" /><input name="organization" required minLength={2} placeholder="Onde trabalha" className="min-h-11 rounded-lg border bg-white px-3 text-sm" /></div><button className="mt-4 min-h-11 rounded-lg bg-[#24231F] px-5 text-sm font-bold text-white">Confirmar cadastro</button></form> : null}
      {!user ? <p className="mt-6 rounded-lg border border-[#E6E2DA] p-4 text-sm text-[#625E59]">Faça <Link className="font-bold underline" href={`/login?next=/community/events/${event.slug}`}>login</Link> para acompanhar discussões e materiais do evento.</p> : null}
      {canContribute ? <section className="mt-8 border-t border-[#ECECE8] pt-6"><h2 className="text-lg font-bold">Materiais compartilhados</h2><p className="mt-1 text-xs text-[#77746E]">Participantes confirmados e administradores podem adicionar arquivos diretamente ao evento.</p><form action={shareEventResource} className="mt-4 grid gap-3 rounded-xl border border-[#E6E2DA] bg-[#F5F1E8] p-4"><input type="hidden" name="event_id" value={event.id} /><div className="grid gap-3 sm:grid-cols-2"><input name="title" required minLength={2} placeholder="Título do arquivo" className="min-h-11 rounded-lg border border-[#D8D3C9] bg-white px-3 text-sm outline-none focus:border-[#D9470F]" /><select name="kind" className="min-h-11 rounded-lg border border-[#D8D3C9] bg-white px-3 text-sm"><option value="foto">Foto</option><option value="documento">Documento</option><option value="outro">Outro arquivo</option></select></div><input name="file" required type="file" accept="image/jpeg,image/png,image/webp,application/pdf,.doc,.docx" className="block min-h-11 w-full rounded-lg border border-dashed border-[#C9C2B6] bg-white px-3 py-2 text-xs file:mr-3 file:rounded-md file:border-0 file:bg-[#24231F] file:px-3 file:py-2 file:text-xs file:font-bold file:text-white" /><p className="text-[10px] text-[#77746E]">JPG, PNG, WEBP, PDF, DOC ou DOCX · até 10 MB</p><textarea name="description" rows={2} placeholder="Descrição (opcional)" className="rounded-lg border border-[#D8D3C9] bg-white p-3 text-sm outline-none focus:border-[#D9470F]" /><button className="min-h-11 w-fit rounded-lg bg-[#24231F] px-5 text-sm font-bold text-white">Adicionar ao evento</button></form><div className="mt-5 space-y-3">{resources?.map(item => <a key={item.id} href={item.storage_path ? `/api/community/events/resources/${item.id}` : item.resource_url ?? '#'} target="_blank" rel="noreferrer" className="block rounded-lg border border-[#E4E2DD] bg-white p-3 hover:border-[#FFB99E]"><p className="text-sm font-bold">{item.title} <span className="ml-1 text-[9px] uppercase text-[#D9470F]">{item.kind}</span></p>{item.description ? <p className="mt-1 text-xs text-[#716B65]">{item.description}</p> : null}</a>)}{!resources?.length ? <p className="text-sm text-[#77746E]">Ainda não há arquivos compartilhados.</p> : null}</div></section> : null}
      {isMember ? <section className="mt-8 border-t border-[#ECECE8] pt-6"><h2 className="text-lg font-bold">Discussões do evento</h2>{discussions?.length ? <div className="mt-3 space-y-3">{discussions.map(post => <Link key={post.id} href={`/community?post=${post.id}`} className="block rounded-lg border border-[#E4E2DD] p-3 hover:border-[#FFB99E]"><p className="text-sm font-bold">{post.title}</p><p className="mt-1 line-clamp-2 text-xs text-[#716B65]">{post.body}</p></Link>)}</div> : <p className="mt-2 text-sm text-[#77746E]">A discussão será criada pelos participantes.</p>}</section> : null}
    </article>
  </main>
}
