-- Both projects share the same RLS, lead review, revisions and collaboration rooms.
alter table public.contract_map_sections drop constraint contract_map_sections_journey_check;
alter table public.contract_map_sections add constraint contract_map_sections_journey_check check (journey in ('contract-lifecycle','clm-migration','open-playbook'));
alter table public.contract_map_sections drop constraint contract_map_sections_id_check;
alter table public.contract_map_sections add constraint contract_map_sections_id_check check (id in ('solicitacao','triagem','elaboracao','negociacao','aprovacao','assinatura','execucao','renovacao','contexto','processos','maturidade','requisitos','dados-legado','viabilidade','fornecedores','piloto','contratacao','migracao','adocao','evolucao','playbook-contexto','playbook-posicoes','playbook-limites','playbook-aprovacoes','playbook-governanca'));
insert into public.contract_map_sections(id,title,position,content,journey) values ('playbook-contexto','Contexto e escopo',201,'{"type": "doc", "content": [{"type": "paragraph", "content": [{"type": "text", "text": "Identifique os tipos de contrato, países, situações e objetivos que este playbook deve cobrir."}]}, {"type": "paragraph", "content": [{"type": "text", "text": "Estrutura inicial para construção coletiva. Ainda não contém posições contratuais aprovadas."}]}]}'::jsonb,'open-playbook');
insert into public.contract_map_sections(id,title,position,content,journey) values ('playbook-posicoes','Posições de negociação',202,'{"type": "doc", "content": [{"type": "paragraph", "content": [{"type": "text", "text": "Acrescente um título para cada tema. Registre a posição proposta, a justificativa, as evidências e o contexto em que ela faz sentido."}]}, {"type": "paragraph", "content": [{"type": "text", "text": "Estrutura inicial para construção coletiva. Ainda não contém posições contratuais aprovadas."}]}]}'::jsonb,'open-playbook');
insert into public.contract_map_sections(id,title,position,content,journey) values ('playbook-limites','Alternativas e limites',203,'{"type": "doc", "content": [{"type": "paragraph", "content": [{"type": "text", "text": "Para cada tema, descreva as alternativas aceitáveis, os limites da negociação e as situações que exigem análise específica."}]}, {"type": "paragraph", "content": [{"type": "text", "text": "Estrutura inicial para construção coletiva. Ainda não contém posições contratuais aprovadas."}]}]}'::jsonb,'open-playbook');
insert into public.contract_map_sections(id,title,position,content,journey) values ('playbook-aprovacoes','Exceções e aprovações',204,'{"type": "doc", "content": [{"type": "paragraph", "content": [{"type": "text", "text": "Descreva quando pedir aprovação, quem deve avaliar e quais informações precisam acompanhar o pedido."}]}, {"type": "paragraph", "content": [{"type": "text", "text": "Estrutura inicial para construção coletiva. Ainda não contém posições contratuais aprovadas."}]}]}'::jsonb,'open-playbook');
insert into public.contract_map_sections(id,title,position,content,journey) values ('playbook-governanca','Revisão e manutenção',205,'{"type": "doc", "content": [{"type": "paragraph", "content": [{"type": "text", "text": "Defina responsáveis pela revisão, critérios para atualizar posições e como registrar decisões e aprendizados."}]}, {"type": "paragraph", "content": [{"type": "text", "text": "Estrutura inicial para construção coletiva. Ainda não contém posições contratuais aprovadas."}]}]}'::jsonb,'open-playbook');
insert into public.contract_map_revisions(section_id,version,content,note) select id,version,content,'Estrutura inicial do Playbook aberto; sem posições contratuais aprovadas (MIT)' from public.contract_map_sections where journey='open-playbook';
