import { act, cleanup, fireEvent, render, screen, waitFor } from '@testing-library/react'
import { afterEach, beforeEach, expect, it, vi } from 'vitest'
const mocks = vi.hoisted(() => ({ otp: vi.fn(), recover: vi.fn(), password: vi.fn(), push: vi.fn(), refresh: vi.fn() }))
vi.mock('@/lib/supabase', () => ({ createClient: () => ({ auth: { signInWithOtp: mocks.otp, resetPasswordForEmail: mocks.recover, signInWithPassword: mocks.password } }) }))
vi.mock('next/navigation', () => ({ useRouter: () => ({ push: mocks.push, refresh: mocks.refresh }) }))
vi.mock('@/components/community/ClubLanguage', () => ({ useClubLanguage: () => ({ t: (s: string, values: Record<string, string> = {}) => s.replace(/\{(\w+)\}/g, (_, key) => values[key]) }), ClubLanguageSelect: () => null }))
vi.mock('@/components/community/GoogleSignIn', () => ({ GoogleSignIn: () => null }))
import LoginPage from '@/app/login/page'
beforeEach(() => { vi.resetAllMocks(); window.history.replaceState({}, '', '/login?next=%2Fcommunity%2Fcalendar'); for (const mock of [mocks.otp, mocks.recover, mocks.password]) mock.mockResolvedValue({ error: null }) })
afterEach(() => { cleanup(); vi.useRealTimers() })
const email = () => fireEvent.change(screen.getByLabelText('Email'), { target: { value: 'Member@Example.com' } })
it('sends a login link without a password or creating a new user and allows resend after a minute', async () => {
  vi.useFakeTimers()
  render(<LoginPage />); email()
  expect(screen.queryByLabelText('Senha')).toBeNull()
  await act(async () => { fireEvent.click(screen.getByRole('button', { name: 'Receber link por email' })) })
  expect(mocks.otp).toHaveBeenCalledWith({ email: 'member@example.com', options: { shouldCreateUser: false, emailRedirectTo: `${window.location.origin}/auth/confirm?next=%2Fcommunity%2Fcalendar` } })
  expect(screen.getByRole('status')).toHaveTextContent('você receberá um link para entrar')
  expect(screen.getByRole('button', { name: 'Reenviar em 60s' })).toBeDisabled()
  for (let i = 0; i < 60; i++) await act(async () => { vi.advanceTimersByTime(1000) })
  await act(async () => { fireEvent.click(screen.getByRole('button', { name: 'Reenviar link' })) })
  expect(mocks.otp).toHaveBeenCalledTimes(2)
})
it('recovery does not require the forgotten password and preserves the destination', async () => {
  render(<LoginPage />); email()
  fireEvent.click(screen.getByRole('button', { name: 'Usar senha' }))
  fireEvent.click(screen.getByRole('button', { name: 'Esqueci minha senha' }))
  expect(screen.queryByLabelText('Senha')).toBeNull()
  fireEvent.click(screen.getByRole('button', { name: 'Enviar link de recuperação' }))
  await waitFor(() => expect(mocks.recover).toHaveBeenCalledWith('member@example.com', { redirectTo: `${window.location.origin}/auth/confirm?next=%2Fset-password%3Fnext%3D%252Fcommunity%252Fcalendar` }))
  expect(await screen.findByRole('status')).toHaveTextContent('redefinir a senha')
})
it('keeps password sign-in available', async () => {
  render(<LoginPage />); email(); fireEvent.click(screen.getByRole('button', { name: 'Usar senha' }))
  fireEvent.change(screen.getByLabelText('Senha'), { target: { value: 'test-only-password' } })
  fireEvent.click(screen.getByRole('button', { name: /^Entrar$/ }))
  await waitFor(() => expect(mocks.push).toHaveBeenCalledWith('/community/calendar'))
  expect(mocks.password).toHaveBeenCalledWith({ email: 'member@example.com', password: 'test-only-password' })
})
it('shows email throttling instead of reporting delivery', async () => {
  mocks.otp.mockResolvedValue({ error: { status: 429, code: 'over_email_send_rate_limit' } })
  render(<LoginPage />); email(); fireEvent.click(screen.getByRole('button', { name: 'Receber link por email' }))
  expect(await screen.findByRole('alert')).toHaveTextContent('Muitas tentativas')
  expect(screen.queryByRole('status')).toBeNull()
})
it('recovers from a network failure without leaving the form disabled', async () => {
  mocks.otp.mockRejectedValue(new Error('offline'))
  render(<LoginPage />); email(); fireEvent.click(screen.getByRole('button', { name: 'Receber link por email' }))
  expect(await screen.findByRole('alert')).toHaveTextContent('Não foi possível conectar')
  expect(screen.getByRole('button', { name: 'Receber link por email' })).toBeEnabled()
})
it('explains an expired link and offers a fresh one', () => {
  window.history.replaceState({}, '', '/login?error=confirmation_failed')
  render(<LoginPage />)
  expect(screen.getByRole('alert')).toHaveTextContent('Este link expirou')
  expect(screen.getByRole('button', { name: 'Receber link por email' })).toBeEnabled()
})
