import { beforeEach, afterEach, expect, it, vi } from 'vitest'
import { fireEvent, render, screen, waitFor, cleanup } from '@testing-library/react'
import { MemberApiKey, MemberApiKeyIndicator } from '@/components/community/MemberApiKey'
const fetchMock = vi.fn()
beforeEach(() => { vi.stubGlobal('fetch', fetchMock); fetchMock.mockReset(); fetchMock.mockResolvedValue({ ok: true, json: async () => ({ connection: null, available: true }) }) })
afterEach(() => { cleanup(); vi.unstubAllGlobals() })
it('requires explicit consent, submits the key, clears the input and supports disconnect', async () => {
  render(<MemberApiKey />)
  const input = await screen.findByLabelText('Chave de API da OpenAI')
  const button = screen.getByRole('button', { name: 'Validar e conectar' })
  expect(button).toBeDisabled()
  fireEvent.change(input, { target: { value: 'sk-proj-test-key-for-unit-testing-only' } })
  fireEvent.click(screen.getByRole('checkbox'))
  fetchMock.mockResolvedValueOnce({ ok: true, json: async () => ({ connection: { provider: 'openai', model: 'gpt-4.1-mini', last_four: 'only' }, available: true }) })
  fireEvent.click(button)
  await screen.findByText('Chave conectada para uso adicional quando seus créditos do Club forem insuficientes.')
  expect(input).toHaveValue('')
  expect(JSON.parse(fetchMock.mock.calls[1][1].body)).toEqual({ api_key: 'sk-proj-test-key-for-unit-testing-only', consent: true })
  expect(screen.getByRole('checkbox')).not.toBeChecked()
  fireEvent.click(screen.getByRole('button', { name: 'Remover chave' }))
  await screen.findByText('Chave removida. As próximas gerações dependerão do saldo de créditos do Club.')
  expect(fetchMock.mock.calls[2][1].method).toBe('DELETE')
})
it('clears a rejected secret and keeps the old connection visible', async () => {
  fetchMock.mockResolvedValueOnce({ ok: true, json: async () => ({ connection: { provider: 'openai', last_four: '1234' }, available: true }) })
  render(<MemberApiKey />)
  const input = await screen.findByLabelText('Chave de API da OpenAI')
  fireEvent.change(input, { target: { value: 'sk-proj-test-key-for-unit-testing-only' } }); fireEvent.click(screen.getByRole('checkbox'))
  fetchMock.mockResolvedValueOnce({ ok: false, json: async () => ({ error: 'invalid_api_key' }) })
  fireEvent.click(screen.getByRole('button', { name: 'Validar e substituir' }))
  await waitFor(() => expect(screen.getByRole('alert')).toHaveTextContent('A OpenAI não aceitou a chave'))
  expect(input).toHaveValue(''); expect(screen.getByText(/••••1234/)).toBeInTheDocument()
})
it('shows who pays in the agent and refreshes after a connection changes', async () => {
  render(<MemberApiKeyIndicator />)
  await screen.findByText('Usando a IA do Club Pro')
  fetchMock.mockResolvedValueOnce({ ok: true, json: async () => ({ connection: { provider: 'openai', last_four: '1234' } }) })
  window.dispatchEvent(new Event('club-api-key-changed'))
  await screen.findByText('API OpenAI conectada para uso adicional')
  expect(screen.getByRole('link', { name: 'Gerenciar chave de API' })).toHaveAttribute('href', '/community/profile#api-key')
})
