import { beforeEach, describe, it, expect, vi } from 'vitest'
import worker from '../cloudflare-landing/_worker.js'
const upstream = vi.fn()
beforeEach(() => { vi.stubGlobal('fetch', upstream); upstream.mockReset() })
describe('OpenCLM canonical path proxy', () => {
  it('preserves static Dev pages', async () => { const assets = vi.fn().mockResolvedValue(new Response('static')); const result = await worker.fetch(new Request('https://legalops.dev/mapa-contratos/'), { ASSETS: { fetch: assets } }); expect(await result.text()).toBe('static'); expect(upstream).not.toHaveBeenCalled() })
  it('canonicalizes the entrypoint', async () => { const result = await worker.fetch(new Request('https://legalops.dev/openclm?x=1'), {}); expect(result.status).toBe(308); expect(result.headers.get('location')).toBe('https://legalops.dev/openclm/?x=1') })
  it('keeps POST bodies and only the OpenCLM session', async () => { upstream.mockResolvedValue(new Response('{}', { headers: { 'Set-Cookie': 'openclm_session=new; Path=/openclm/; HttpOnly; Secure' } })); const result = await worker.fetch(new Request('https://legalops.dev/openclm/api/v1/auth/login', { method: 'POST', body: '{"test":true}', headers: { Cookie: 'other=private; openclm_session=abc', Origin: 'https://legalops.dev', 'X-OpenCLM': '1' } }), {}); const req = upstream.mock.calls[0][0]; expect(req.url).toBe('https://openclm.leonn.dev/openclm/api/v1/auth/login'); expect(req.headers.get('cookie')).toBe('openclm_session=abc'); expect(req.headers.get('origin')).toBe('https://legalops.dev'); expect(req.headers.get('x-openclm')).toBe('1'); expect(await req.text()).toBe('{"test":true}'); expect(result.headers.get('set-cookie')).toContain('Path=/openclm/'); expect(result.headers.get('cache-control')).toBe('no-store') })
  it('keeps redirects inside the new app path', async () => { upstream.mockResolvedValue(new Response(null, { status: 303, headers: { Location: '/?salesforce=connected' } })); const result = await worker.fetch(new Request('https://legalops.dev/openclm/api/v1/integrations/salesforce/callback'), {}); expect(result.headers.get('location')).toBe('https://legalops.dev/openclm/?salesforce=connected') })
  it('does not rebase external OAuth redirects', async () => { upstream.mockResolvedValue(new Response(null, { status: 303, headers: { Location: 'https://test.salesforce.com/authorize' } })); const result = await worker.fetch(new Request('https://legalops.dev/openclm/api/v1/integrations/salesforce/connect'), {}); expect(result.headers.get('location')).toBe('https://test.salesforce.com/authorize') })
})
it('forwards websocket upgrades without copying session cookies or reconstructing the upgrade response',async()=>{const response={status:101,webSocket:{}};upstream.mockResolvedValue(response);expect(await worker.fetch(new Request('https://legalops.dev/collaboration',{headers:{Upgrade:'websocket',Cookie:'private=1',Authorization:'Bearer other'}}),{})).toBe(response);const request=upstream.mock.calls[0][0];expect(request.url).toBe('https://openclm.leonn.dev/collaboration');expect(request.headers.has('cookie')).toBe(false);expect(request.headers.has('authorization')).toBe(false)})
it('requires an upgrade for the collaboration endpoint',async()=>{expect((await worker.fetch(new Request('https://legalops.dev/collaboration'),{})).status).toBe(426);expect(upstream).not.toHaveBeenCalled()})

it('preserves the mount prefix for FastAPI static assets',async()=>{upstream.mockResolvedValue(new Response('css'));await worker.fetch(new Request('https://legalops.dev/openclm/static/styles.css'),{});expect(upstream.mock.calls[0][0].url).toBe('https://openclm.leonn.dev/openclm/static/styles.css')})
